### PR TITLE
CORE-1647: Switch to `labstack/echo` version 4.

### PR DESCRIPTION
**Pull request by slr71**
The previous version of `labstack/echo` relied on a JWT library that is no longer maintained, and contains a security vulnerability. Version 4, uses a different JWT library so that it's not affected by the security vulnerability.

Version 2.0.0 of this module will be published at the same time so that existing code that uses previous versions of `labstack/echo` can still use version 1.0.0 of this module. Furthermore, no updates will be made to version 1.0.0 of this module, so a new branch will not be created for the v2 series.

A changelog has also been created to make it easier to identify the changes in each version of this module. We don't expect changes to this module to be common at this time, but creating a changelog is easy.

### CODE REVIEW

**Review by ianmcorvidae — APPROVED** [review]
Looks reasonable to me. Nice that it just works to run a `go get`!

**Comment by slr71** [comment]
> Looks reasonable to me. Nice that it just works to run a `go get`!

Yeah, I was very pleasantly surprised when I noticed that that updated all of the imports in the code for me. 😌

**Comment by slr71** [comment]
Thanks for the review!

**Comment by slr71** [comment]
Oh, this is interesting. It updated the imports automatically when I did this in another code base, but not this one. I'll have to take a closer look at this. 😖

**Comment by slr71** [comment]
Now I'm questioning what happened, because I haven't been able to reproduce the updates to the imports yet. At any rate, the updates have been made, and I'm going to merge the changes. Sorry about the confusion there.

Thanks for the review!

**Pull request merged**
